// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/authentication/authentication.proto

package authentication

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Authentication service

type AuthenticationService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Authentication_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Authentication_PingPongService, error)
}

type authenticationService struct {
	c    client.Client
	name string
}

func NewAuthenticationService(name string, c client.Client) AuthenticationService {
	return &authenticationService{
		c:    c,
		name: name,
	}
}

func (c *authenticationService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Authentication.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Authentication_StreamService, error) {
	req := c.c.NewRequest(c.name, "Authentication.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &authenticationServiceStream{stream}, nil
}

type Authentication_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type authenticationServiceStream struct {
	stream client.Stream
}

func (x *authenticationServiceStream) Close() error {
	return x.stream.Close()
}

func (x *authenticationServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *authenticationServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *authenticationServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *authenticationServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *authenticationService) PingPong(ctx context.Context, opts ...client.CallOption) (Authentication_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Authentication.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &authenticationServicePingPong{stream}, nil
}

type Authentication_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type authenticationServicePingPong struct {
	stream client.Stream
}

func (x *authenticationServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *authenticationServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *authenticationServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *authenticationServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *authenticationServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *authenticationServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Authentication service

type AuthenticationHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Authentication_StreamStream) error
	PingPong(context.Context, Authentication_PingPongStream) error
}

func RegisterAuthenticationHandler(s server.Server, hdlr AuthenticationHandler, opts ...server.HandlerOption) error {
	type authentication interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Authentication struct {
		authentication
	}
	h := &authenticationHandler{hdlr}
	return s.Handle(s.NewHandler(&Authentication{h}, opts...))
}

type authenticationHandler struct {
	AuthenticationHandler
}

func (h *authenticationHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.AuthenticationHandler.Call(ctx, in, out)
}

func (h *authenticationHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.AuthenticationHandler.Stream(ctx, m, &authenticationStreamStream{stream})
}

type Authentication_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type authenticationStreamStream struct {
	stream server.Stream
}

func (x *authenticationStreamStream) Close() error {
	return x.stream.Close()
}

func (x *authenticationStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *authenticationStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *authenticationStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *authenticationStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *authenticationHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.AuthenticationHandler.PingPong(ctx, &authenticationPingPongStream{stream})
}

type Authentication_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type authenticationPingPongStream struct {
	stream server.Stream
}

func (x *authenticationPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *authenticationPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *authenticationPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *authenticationPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *authenticationPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *authenticationPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
